[package]
name = "druid_garden_chiapos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit-vec = "*"
sha2 = "*"
blake3 = "1.3.1"
lazy_static = "1.4.0"